name: CI
on:
  push:
    branches:
      - main
      - master
jobs:
  push1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      - run: test
      - run: build
      - run: deploy
      
